anypoint:
  platform:
    autodiscovery: "16473460"
snowflake:
  database: "CAMBIUM"
  table: "BILL_PAID_JOBS"
  warehouse: "CAMBIUM"
mq:
  destination: "bill-paid-events"
  missingQuoteDestination: "bill-paid-event-quote-not-found"
contract-sapi:
  host: "contract-sapi.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basePath: "/api/"